export const projects = [
  {
    title: 'Real Estate-UAE',
    description: "Using Next.js, Node, Express and Bayut API from rapidapi.com, this real estate app called CodePipr Real Estate was built from start to finish by me. CodePipr Real Estate contains all the working parts of a functioning everyday Real Estate app ranging from property search using desired filters, selection to property look-up.",
      image: '/images/realestate-uae.png',
      tags: ['Express ', 'Firebase ', 'Chakra UI ', 'Node ', 'Next.js',],
    source: 'https://github.com/deddypiper/RealEstate-UAE',
    visit: 'uae-real-estate-one.vercel.app',
    id: 0,
  },
  // {
  //   title: 'E-commerce WebApp',
  //   description: "Using React, Commerce.js, Stripe and Node this e-commerce app called Piper E-commerce shop was built from start to finish by me. Piper E-commerce Shop contains all working parts of a functioning everyday e-commerce app ranging from products selection, cart addition, checkout, card payment to shopping confirmation.",
  //     image: '/images/001.png',
  //     tags: ['Commerce.js', 'Stripe', 'React', 'Node'],
  //   source: 'https://github.com/deddypiper/E-commerce_Shop',
  //   visit: 'https://codepipr-commerce-shop.netlify.app/',
  //   id: 1,
  // },
  {
    title: 'CryptoDom',
    description: "CryptoDom is Cryptocurrency inclined app featuring servicessuch as cryptocurrency conversion, latest crypto news, general and specific cryptocurrencies information that will aid anyone in understanding cryptocurrencies and make decisions. This app was built with React, Chart.js, Bing news REST API and stylishly beautified with Ant Design.",
      image: '/images/crypto.png',
      tags: ['REST API ', 'Ant Design ', 'React ', 'Chart.js'],
    source: 'https://github.com/deddypiper/CryptoDom',
    visit: 'crypto-dom.vercel.app',
    id: 2,
  },
  {
    title: 'Voyager Guide',
    description: "The Voyager Guide is an app that helps one plan a visit to any desired restaurants, attractions or relaxation spots made possible with Google Map, React and Material UI for styling.",
      image: '/images/voyager.png',
      tags: ['REST API ', 'Google Map API ', 'React ', 'CSS3'],
    source: 'https://github.com/deddypiper/Voyager-Guide',
    visit: 'voyager-guide.vercel.app',
    id: 3,
  },
  {
    title: 'Google Clone',
    description: "This Google Search Clone featuring video, image and news search was built using React.js, styled with Tailwind CSS and also integrated with google search api from rapidapi.com.", 
      image: '/images/google.png',
      tags: ['React ', 'Tailwind CSS'],
    source: 'https://github.com/deddypiper/Google-Clone',
    visit: 'google-clone-two-coral.vercel.app',
    id: 4,
  },
  {
    title: 'E-commerce WebApp',
    description: "Using React, Commerce.js, Stripe and Node this e-commerce app called Piper E-commerce shop was built from start to finish by me. Piper E-commerce Shop contains all working parts of a functioning everyday e-commerce app ranging from products selection, cart addition, checkout, card payment to shopping confirmation.",
      image: '/images/001.png',
      tags: ['Commerce.js ', 'Stripe ', 'React', 'Node'],
    source: 'https://github.com/deddypiper/E-commerce_Shop',
    visit: 'https://codepipr-commerce-shop.netlify.app/',
    id: 5,
  },
  {
    title: 'Colour-Hue Generator',
    description: "This is an app that takes a color's hex-code and returns varieties of the color in ascension to white color and descension to black color. In this project React and Node was employed for effective development.",
      image: '/images/003.png',
      tags: ['React ', 'Tailwind CSS'],
    source: 'https://github.com/deddypiper/Colour_Generator',
    visit: 'https://colour-generatorr.netlify.app/',
    id: 6,
  },
  {
    title: 'Breathing App',
    description:"I built this breathing app using HTML, CSS and Vanilla JavaScript. A simple but yet powerful tool designed to regulate breathing and help one's mind relax. A mental health tool.",
    image: '/images/002.png',
    tags: ['JavaScript ', 'CSS ', 'HTML'],
    source: '#',
    visit: 'https://codepipr-breathing-app.netlify.app/',
    id: 7,
  },
  {
    title: 'Submenu',
    description: "This responsive subdivision of a realtime WebApp was built using React and CSS to offer optimum user xperience to web users.",
    image: '/images/004.png',
    tags: ['React ', 'CSS'],
    source: 'https://github.com/deddypiper/Submenus',
    visit: 'https://submenus.netlify.app/',
    id: 8,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Began my journey into the fascinating world of Web Development', },
  { year: 2020, text: 'Collaborated on a lot of projects to hone and improve my acquired skills', },
  { year: 2021, text: 'Works as a freelance Web developer ', },
];